classdef FigsExt < handle
properties
    ExtEmp

    dLMCR
    dLmCR
    dTTCRR

    pLMCR
    pLmCR
end
properties(Hidden)
    ExtEmp_
    dLMCR_
    dLmCR_
    dTTCRR_

    pLMCR_
    pLmCR_
end
methods
%- GET ExtEmp
    function out=get.ExtEmp(obj)
        if isempty(obj.ExtEmp_)
            S=struct('bBino',false','bZer',false,'fitType',0);
            obj.ExtEmp_=ExtEmp(obj.dims,obj.subjs,obj.passes,obj.model,false,S);
        end
        out=obj.ExtEmp_;
    end
%- GET DEMOS
    function out=get.dLmCR(obj)
        if isempty(obj.dLmCR_)
            args={...
                     'bAnimate',false, ...
                     'fitType',0, ...
                     'bAll',false, ...
                     ...
                     'VarL',1, ...
                     'm',[1 1.5 2.6], ...
                     'covLB',[], ...
                     'bCorr',true, ...
                     'model','LmCR', ...
                     'FRCFlds',[] ...
            };
            obj.dLmCR_=ExtDemo.fromEP(obj.dims,obj.subjs,obj.passes,obj.model,false,args{:});
        end
        out=obj.dLmCR_;
    end
    function out=get.dTTCRR(obj)
        if isempty(obj.dTTCRR_)
            args={...
                     'bAnimate',false, ...
                     'fitType',0, ...
                     'bAll',false, ...
                     ...
                     'T2',0.8, ...
                     'T3',1.5, ...
                     'Rho22',0.4, ...
                     'Rho33',0.3, ...
                     'covLB',[], ...
                     'bCorr',true, ...
                     'model','TTCRR', ...
                     'FRCFlds',[] ...
            };
            obj.dTTCRR_=ExtDemo.fromEP(obj.dims,obj.subjs,obj.passes,obj.model,false,args{:});
        end
        out=obj.dTTCRR_;
    end
    function out=get.dLMCR(obj)
        if isempty(obj.dLMCR_)
            args=   {...
                     'bAnimate',false, ...
                     'fitType',0, ...
                     'bAll',false, ...
                     ...
                     'VarL',1, ...
                     'M',[1 1.5 2.6], ...
                     'covLB',[], ...
                     'bCorr',true, ...
                     'model','LMCR', ...
                     'FRCFlds',[] ...
            };
            obj.dLMCR_=ExtDemo.fromEP(obj.dims,obj.SUBJS,obj.passes,obj.model,false,args{:});
        end
        out=obj.dLMCR_;
    end
%- GET PREDICTS
    function get.pLmCR(bNew)
        if isempty(obj.pLmCR_)
            args={...
                     'eModel','LmCR', ...
                     'fitType', 0, ...
                     'bLog',    false, ...
                     'binNums', [], ...
                     'flds',[], ...
                     ...
                     'oMargin',[2 1.5 3 4], ...
                     'iMargin',[1 0 2 1], ...
                     'oUnits','char', ...
                     'iUnits','char', ...
                     ...
                     'nCov',1000, ...
                     'lCov',[-4 4], ...
                     'VarL',1, ...
                     'M',[] ...
            };
            obj.pLmCR_=ExtP(obj.dims,obj.subjs,obj.passes,obj.model,false,args{:});
        end
        out=obj.pLmCR_;
    end
    function get.pLMCR(bNew)
        if isempty(obj.pLMCR_)
            args=   {...
                     'eModel','LMCR', ...
                     'fitType', 0, ...
                     'bLog',    false, ...
                     'binNums', [], ...
                     'flds',[], ...
                     ...
                     'oMargin',[2 1.5 3 4], ...
                     'iMargin',[1 0 2 1], ...
                     'oUnits','char', ...
                     'iUnits','char', ...
                     ...
                     'nCov',1000, ...
                     'lCov',[-4 4], ...
                     'VarL',1, ...
                     'M',[] ...
            };
            obj.pLMCR_=ExtP(dims,SUBJS,passes,model,bNew,args{:});
        end
        out=obj.pLMCR_;
    end
end
end
